#Specify if this minecraft server is the primary minigames server on this machine.
#The primary server will download config updates from the controller and apply them.
primary: true

# Specify bungeecord details of this server
bungee:
  name: "server1"
  hub: "hub1"

# Specify the config and maps directories
directories:
  config: "/srv/minigames/config"
  maps: "/srv/minigames/maps"
  assets: "/srv/minigames/assets"

# Specifies if this server has a ramdisk
ramdisk:
  enable: true
  directory: "/tmp"

# Specify which modules are enabled
modules:
  game: true
  hub: false

# Specify database connection details
database:
  url: "jdbc:mysql://localhost:3306/minigames"
  driver: "com.mysql.jdbc.Driver"
  user: "username"
  password: "password"
  min_connections: 1
  max_connections: 10