
# TODO Specify the details of the minigames controller you connect to
controller:
  hostname: "minigames-controller.com"
  port: 30824
  private_key: "my_private_key_file.key"

  #Specify if this minecraft server is the primary minigames server on this machine.
  #The primary server will download config updates from the controller and apply them.
  primary: true

# TODO Specify bungeecord details of this server
bungee:
  name: "server1"

# TODO Specify the config and maps directories
directories:
  config: "/srv/minigames/config"
  map_config: "/srv/minigames/config/maps"
  maps: "/srv/minigames/maps"
  assets: "/srv/minigames/assets"

# TODO Specifies if this server has a ramdisk
ramdisk:
  enable: true
  directory: "/tmp"