name: "MinigamesBase"
version: "${project.version}"
main: "com.ithinkrok.minigames.base.BasePlugin"
author: "ithinkrok"
depend: ["HologramAPI", "ProtocolLib"]
softdepend: ["DisguiseCraft", "LibsDisguises"]
database: true

permissions:

  mg.base.admin:
    description: "Gives all admin commands"
    default: "op"
    children:
      mg.base.mg: true
      mg.base.gamestate: true
      mg.base.countdown: true

  mg.base.user:
    description: "Gives all user commands"
    default: true
    children:
      mg.base.help: true

  mg.base.mg:
    description: "Allows use of /mg"
    default: false

  mg.base.gamestate:
    description: "Allows use of /gamestate"
    default: false

  mg.base.countdown:
    description: "Allows use of /countdown"
    default: false

  mg.base.help:
    description: "Allows use of /help"
    default: false

commands:
  minigames:
    description: "Execute minigames commands as the console"
    aliases: ["mg"]
    permission: "mg.base.mg"
    usage: "/<command> <gamegroup> <minigames command> [minigames command arguments...]"