
lang_files:
  - "global/global.lang"

currencies:
  game:
    singular: "coin"
    plural: "coins"
    symbol: "$"
    format: "$%s"
    decimals: 0

shared_objects:
  rewards:
    mult:
      copper: "players > 0"
      silver: "players > 3"
      gold: "players > 7"
    participation:
      copper: "75 * (1 + ln((players + 3) / 3))"
      silver: "8 * (pow(players / 4, 1.2))"
      gold: "2 * ((players - 4) / 4)"
  game_rewards:
    mult: "pow(time/10, 0.75)"

commands:
  ahelp:
    description: "Shows all command help"
    permission: "mg.base.help"
    usage: "/<command>"
    class: "com.ithinkrok.minigames.util.command.HelpCommand"
  help:
    description: "Shows minigames command help"
    aliases: ["?"]
    permission: "mg.base.help"
    usage: "/<command>"
    class: "com.ithinkrok.minigames.util.command.HelpCommand"
    config:
      all: false
  gamestate:
    description: "Changes the GameState of the current GameGroup"
    aliases: ["gs", "gstate"]
    permission: "mg.base.gamestate"
    usage: "/<command> <gamestate>"
    class: "com.ithinkrok.minigames.util.command.GameStateCommand"
  countdown:
    description: "Modifies countdowns"
    aliases: ["cd", "cdown", "cdwn"]
    permission: "mg.base.countdown"
    usage: |
      /<command> add/set <amount>
      /<command> finish/cancel
      /<command> start <name> <seconds> <localestub>
    class: "com.ithinkrok.minigames.util.command.CountdownCommand"
  debug:
    description: "Various debug subcommands"
    aliases: ["mgd", "mgdebug"]
    permission: "mg.base.debug"
    usage: "/<command> <custom/level/team/kit/money> [subcommandargs]"
    class: "com.ithinkrok.minigames.util.command.DebugCommand"
  shop:
    description: "Show the rewards shop"
    aliases: ["mgshop", "mgrewards"]
    permission: "mg.base.shop"
    usage: "/<command>"
    class: "com.ithinkrok.minigames.util.command.ShopCommand"

custom_items:
  hub_returner:
    display_name_locale: "hub_returner.name"
    description_locale: "hub_returner.desc"
    material: "BED"
    durability: 14
    listeners:
      hub_return:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.HubTeleporter"