lang_files:
  - "global/global.lang"
  - "hub/hub.lang"

maps:
  hub: "hub/maps/hub.yml"

shared_objects:
  start_info:
    game_state: "hub"
    map: "hub"
  game:
    all_fire: true
    max_players: 250
    default_motd: "Hub sign really"
    chat_prefix: "&7[&3Hub&7] &e"

game_states:
  hub:
    listeners:
      hub:
        class: "com.ithinkrok.minigames.hub.HubListener"
        config:
          signs_config_path: "plugins/MinigamesBase/signs.yml"
          items:
            clear_inventory: true
            custom_items:
              - name: "super_popper"
                slot: 0
              - name: "pvp_sword"
                slot: 1
              - name: "ultra_popper"
                slot: 2
                permission: "donator.ultra_popper"
              - name: "game_chooser"
                slot: 4
              - name: "gamegroups_menu"
                slot: 5
          jump_pads:
            - material: "GOLD_PLATE"
              power: 2.5
              sound: "ENTITY_WITHER_SHOOT"
          super_popper:
            power: 2.0
            victim_locale: "super_popper.victim"
            attacker_locale: "super_popper.attacker"
            pvp_locale: "super_popper.pvp"
            victim_sound: "ENTITY_FIREWORK_LARGE_BLAST"
            attacker_sound: "ENTITY_ARROW_HIT"
          pvp_sword:
            custom_item: "pvp_sword"
            win_sound: "ENTITY_ZOMBIE_VILLAGER_CURE"
            loss_sound: "ENTITY_IRONGOLEM_DEATH"
          welcome:
            title_locale: "welcome.title"
            subtitle_locale: "welcome.subtitle"
          scoreboard:
            title_locale: "scoreboard.title"
            players_online_locale: "scoreboard.players_online"
            lobby_info_locale: "scoreboard.lobby_info"
            games_info_locale: "scoreboard.games_info"
            players_on_hub_locale: "scoreboard.players_on_hub"
          lobby_created_locale: "hub.lobby_created"
          click_join_locale: "hub.click_join_builder"

custom_items:
  game_chooser:
    material: "COMPASS"
    display_name_locale: "game_chooser.name"
    description_locale: "game_chooser.desc"
    listeners:
      game_chooser:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.hub.item.GameChooseMenu"
        config:
          gamegroups:
            - type: "colony_wars"
              slot: 10
              item: "GOLD_INGOT,1,0,&2&lColony Wars"
              teleport: "387.5,141.05,-357.5,-90,0"
              query:
                require_accepting: true
                ranks:
                  - type: "colony_wars"
                  - type: "2x_colony_wars"
                  - type: "12x_colony_wars"
            - type: "tntrun"
              slot: 12
              item: "TNT,1,0,&4&lTNT Run"
              teleport: "345.5,141,-399.5,180,0"
            - type: "one_vs_one"
              slot: 14
              params: ["aqualonia"]
              item: "BLAZE_POWDER,1,0,&2&lOne vs One,&7Map: &aAqualonia"
              teleport: "303.5,141,-357.5,90,0"
            - type: "survival_games"
              slot: 16
              item: "IRON_SWORD,1,0,&1&lSurvival Games"
              teleport: "345.5,141,-315.5,0,0"
            - type: "zombie_escape"
              slot: 2
              item: "SKULL_ITEM,1,2,&4&lZombie Escape"
            - type: "infected"
              slot: 6
              item: "SKULL_ITEM,1,2,&4&lInfected"
            - type: "apocalypse"
              slot: 22
              item: "SKULL_ITEM,1,1,&4&lApocalypse"
          direct_join_enabled_item: "DIAMOND_BLOCK,1,0,&c&lDisable Direct Join"
          direct_join_disabled_item: "COAL_BLOCK,1,0,&a&lEnable Direct Join"
  gamegroups_menu:
    material: "WATCH"
    display_name_locale: "gamegroups_menu.name"
    description_locale: "gamegroups_menu.desc"
    listeners:
      gamegroups_menu:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.hub.item.GameGroupsMenu"
        config:
          gamegroup_type: ""
  pvp_sword:
    material: "DIAMOND_SWORD"
    display_name_locale: "pvp_sword.name"
    description_locale: "pvp_sword.desc"
    enchantments:
      DAMAGE_ALL: 3
    listeners:
      pvp_sword:
        class: "com.ithinkrok.minigames.hub.item.PvpSword"
        config:
          armor:
            helmet: "DIAMOND_HELMET"
            chestplate: "DIAMOND_CHESTPLATE"
            leggings: "DIAMOND_LEGGINGS"
            boots: "DIAMOND_BOOTS"
          start_sound: "ENTITY_BLAZE_HURT"
          end_sound: "ENTITY_CHICKEN_HURT"
  super_popper:
    material: "BOW"
    display_name_locale: "super_popper.name"
    enchantments:
      OXYGEN: 1
    listeners:
      super_popper:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.hub.item.SuperPopper"
  ultra_popper:
    material: "BONE"
    display_name_locale: "ultra_popper.name"
    right_cooldown:
      ability: "ultra_popper"
      timer: "0.5"
    enchantments:
      OXYGEN: 1
    listeners:
      ultra_popper:
        class: "com.ithinkrok.minigames.hub.item.UltraPopper"
        config:
          low_speed: 0.2
          high_speed: 2.0