lang_files:
  - "global/global.lang"
  - "hub/hub.lang"

maps:
  hub: "hub/maps/hub.yml"

shared_objects:
  start_info:
    game_state: "hub"
    map: "hub"
  game:
    all_fire: true
    max_players: 250
    default_motd: "Hub sign really"
    chat_prefix: "&7[&3Hub&7] &e"

game_states:
  hub:
    listeners:
      hub:
        class: "com.ithinkrok.minigames.hub.HubListener"
        config:
          signs_config_path: "plugins/MinigamesBase/signs.yml"
          items:
            clear_inventory: false
            custom_items:
              - name: "super_popper"
                slot: 0
              - name: "game_chooser"
                slot: 4
          jump_pads:
            - material: "GOLD_PLATE"
              power: 2.5
              sound: "ENTITY_WITHER_SHOOT"
          super_popper:
            power: 2.0
            victim_locale: "super_popper.victim"
            attacker_locale: "super_popper.attacker"
            victim_sound: "ENTITY_FIREWORK_LARGE_BLAST"
            attacker_sound: "ENTITY_ARROW_HIT"
          welcome:
            title_locale: "welcome.title"
            subtitle_locale: "welcome.subtitle"

custom_items:
  game_chooser:
    material: "COMPASS"
    display_name_locale: "game_chooser.name"
    description_locale: "game_chooser.desc"
    listeners:
      game_chooser:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.hub.item.GameChooseMenu"
        config:
          gamegroups:
            - type: "colony_wars"
              item: "GOLD_INGOT,1,0,&1&lColony Wars"
              teleport: "387.5,141.05,-357.5,-90,0"
            - type: "tntrun"
              item: "TNT,1,0,&1&lTNT Run"
              teleport: "345.5,141,-399.5,180,0"
            - type: "one_vs_one"
              params: ["aqualonia"]
              item: "BLAZE_POWDER,1,0,&1&lOne vs One,&7Map: &aAqualonia"
              teleport: "303.5,141,-357.5,90,0"
            - type: "survival_games"
              item: "IRON_SWORD,1,0,&1&lSurvival Games"
              teleport: "345.5,141,-315.5,0,0"
          direct_join_enabled_item: "DIAMOND_BLOCK,1,0,&c&lDisable Direct Join"
          direct_join_disabled_item: "COAL_BLOCK,1,0,&a&lEnable Direct Join"
  super_popper:
    material: "BOW"
    display_name_locale: "super_popper.name"
    enchantments:
      OXYGEN: 1
    listeners:
      super_popper:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.hub.item.SuperPopper"