

shared_objects:
  shop:
    items:
      - class: "com.ithinkrok.minigames.util.inventory.Buyable"
        display: "gold_ingot,1,0,&6Copper to Dollar"
        config:
          cost: 1
          currency: "token_copper"
          costs:
            vault: -1
      - class: "com.ithinkrok.minigames.util.inventory.SubInventory"
        display: "iron_ore"
        config:
          name_locale: "shop.ores"
          items:
            - class: "com.ithinkrok.minigames.util.inventory.ItemBuyable"
              config:
                item: "iron_ore,8"
                cost: 800
                currency: "vault"
      - class: "com.ithinkrok.minigames.util.inventory.SubInventory"
        display: "mob_spawner"
        config:
          name_locale: "shop.spawners"
          items:
            - class: "com.ithinkrok.minigames.util.inventory.ItemBuyable"
              config:
                item: "mob_spawner"
                cost: 25000
                currency: "vault"
