
pre_configs:
  - "global/global.yml"
  - "towny/shop.yml"

lang_files:
  - "towny/lang/towny.lang"
#  - "towny/lang/items.lang"

maps:
  towny: "towny/maps/towny.yml"

shared_objects:
  game:
    chat_prefix: "&7[&4Factions&7] &e"
    friendly_fire: true
    no_team_fire: true
    not_in_game_fire: true
    mob_fire: true
    cancel_death: false
  start_info:
    game_state: "towny"
    map: "towny"
  user:
    use_new_combat: true

game_states:
  towny:
    listeners:
      games_join:
        class: "com.ithinkrok.minigames.util.listener.GamesJoinListener"
        config:
          lobby_created_locale: "hub.lobby_created"
          click_join_locale: "hub.click_join_builder"

custom_items: {}