description: "The museum world!"

spawn:
  x: -199950.5
  y: 124.1
  z: -299979.5

worlds:
  map:
    folder: "museum"
    environment: "normal"
    type: "saved"
  map_nether:
    folder: "museum_nether"
    environment: "nether"
    type: "saved"
  map_the_end:
    folder: "museum_the_end"
    environment: "the_end"
    type: "saved"

custom_items:
  warp_chooser:
    display_name_locale: "museum_teleporter.name"
    material: "COMPASS"
    listeners:
      warp:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.WarpChooser"
        config:
          title_locale: "museum_teleporter.title"
          warps: []