description: "The museum world!"



worlds:
  map:
    folder: "museum"
    environment: "normal"
    type: "saved"
    spawn:
      x: -199950.5
      y: 124.1
      z: -299979.5
    game_rules: &game_rules
      doMobLoot: false
      mobGriefing: false
    generator: "void"
  map_nether:
    folder: "museum_nether"
    environment: "nether"
    type: "saved"
    game_rules: *game_rules
    generator: "void"
  map_the_end:
    folder: "museum_the_end"
    environment: "the_end"
    type: "saved"
    game_rules: *game_rules
    generator: "void"

shared_objects:
  museum:
    locations:
      og1:
        pos: "199545,64,-1049597"
        future: "og2"
      og2:
        pos: "225145,64,-1049597"
        past: "og1"
        future: "og3"
      og3:
        pos: "-307335,64,-1305597"
        past: "og2"
      eightworld:
        pos: "-1024000,64,-1024000"
        past: "eightworld-july"
        size: 30000
      eightworld-july:
        pos: "-153600,64,-153600"
        past: "eightworld-dec"
        future: "eightworld"
        size: 30000
      eightworld-dec:
        pos: "-204800,64,-153600"
        future: "eightworld-july"
        size: 30000
      itrf:
        pos: "0,64,0"
        past: "itrf-sep"
        size: 10000
      itrf-sep:
        pos: "-30720,64,-5120"
        future: "itrf"
        past: "itrf-june"
        size: 10000
      itrf-june:
        pos: "-15360,64,10240"
        future: "itrf-sep"
        size: 10000

custom_items:
  time_back:
    display_name_locale: "time_back.name"
    material: "sapling"
    listeners:
      time:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.TimeWarper"
        config:
          to_the_future: false
  time_forward:
    display_name_locale: "time_forward.name"
    material: "eye_of_ender"
    listeners:
      time:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.TimeWarper"
        config:
          to_the_future: true
  warp_chooser:
    display_name_locale: "museum_teleporter.name"
    material: "COMPASS"
    listeners:
      warp:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.WarpChooser"
        config:
          title_locale: "museum_teleporter.title"
          warps:
            - name: "&cOriginal Hut"
              item: "wool,1,14"
              lore: ["Where it all started..."]
              pos: "-180,75,998422"
            - name: "&cOriginal Flair"
              item: "wool,1,14"
              lore: ["Flair is created!"]
              pos: "-216,65,998116"
            - name: "&cFort Fiare"
              item: "wool,1,14"
              lore: ["We gonna burn."]
              pos: "5262,72,998469"
            - name: "&eGigaCavern"
              item: "wool,1,4"
              lore: ["My first proper survival world"]
              pos: "251051,68,-1049598"
            - name: "&eThe Base Between"
              item: "wool,1,4"
              lore: ["To link up GigaCavern and the rest of the Random Seed bases"]
              pos: "251387,70,-1049848"
            - name: "&eFort Factory Mob"
              item: "wool,1,4"
              lore: ["Do you know how to make a mob farm?"]
              pos: "251443,64,-1049008"
            - name: "&eSandy Mines"
              item: "wool,1,4"
              lore: ["Literally the only mine with a (once) working cart system"]
              pos: "251760,30,-1049703"
            - name: "&eThe Vault"
              item: "wool,1,4"
              lore: ["Where better to store your nice diamonds?"]
              pos: "251842,64,-1051083"
            - name: "&aThe Hut (OG1)"
              item: "wool,1,13"
              lore: ["Hooray for the first server!"]
              pos: "199557,68,-1049584"
            - name: "&aCacti and Reeds (OG1)"
              item: "wool,1,13"
              lore: ["The cacti quest has begun. Not that we went far"]
              pos: "199538,64,-1049121"
            - name: "The Great Farm"
              item: "nether_brick"
              lore: ["A competition between ithinkrok and WaterTrickster"]
              pos: "10074,64,-1050767"2
            - name: "Ithinkrok's Factions Spawn"
              lore: ["The server is UP and it's never comin' down"]
              item: "wood,1,3"
              pos: "-147.3,199,350.7,164,33"
            - name: "Castle Base (itrf)"
              item: "wood,1,3"
              pos: "-1296.4,65,981.1,179.5,6.7"
            - name: "Bollandj's Temple (itrf)"
              item: "wood,1,3"
              pos: "-309.4,65,23.4,-100,-10"
            - name: "Cool House, Dirt House (itrf)"
              item: "wood,1,3"
              pos: "-906,70,-2753.5,54,4"
            - name: "The Peacekeeper's Base (itrf)"
              item: "wood,1,3"
              pos: "3377.5,30,1322.7,-252,-2"
            - name: "TheVarden's Base (itrf)"
              lore: ["Owned by MineTurtle67 and aided by mclilgirl and verybigdigger"]
              item: "wood,1,3"
              pos: "-117.5,63,891.5"
            - name: "xxsniper7xx's Base (itrf)"
              item: "wood,1,3"
              pos: "-2550,71,-512,103,-6"
            - name: "Turtle Fort (itrf)"
              item: "wood,1,3"
              pos: "-5801,63,-1434,-96,4"
            - name: "xxsniper7xx's House Build (itrf)"
              lore: ["Looks best with the FLOWS texture pack!"]
              item: "wood,1,3"
              pos: "-619.9,71,-2138.5,-266.7,1"
            - name: "xxsniper7xx's Dwarf Build (itrf)"
              lore: ["I seem to remember running from a zombie..."]
              item: "wood,1,3"
              pos: "-6929.2,64,153.9,-135.8,0"
            - name: "Eightworld Spawn"
              item: "prismarine"
              lore: ["The second world on Ithinkrok's Factions"]
              pos: "-1025925.5,89.5,-1021670.5"
            - name: "Griefed Faction Base (eightworld)"
              item: "prismarine"
              lore: ["bosscamcam123 is the Manager / Boss"]
              pos: "-1025380.5,92,-1021470.5"
            - name: "xxsniper7xx's Base (eightworld)"
              lore: ["Look inside :)"]
              item: "prismarine"
              pos: "-1024292.5,91.5,-1023633.5"
            - name: "Samuel's Drug Pub (eightworld)"
              lore: ["It's a bit of a mess, I know :P"]
              item: "prismarine"
              pos: "-1026355.15,71.03,-1025038.06"
            - name: "Jofly's Home (eightworld)"
              lore: ["People to Spare: bosscamcam123"]
              item: "prismarine"
              pos: "-1024059.5,87.1,-1017374.5"
            - name: "Jofly's Trading Post (eightworld)"
              lore: ["NO REFUNDS"]
              item: "prismarine"
              pos: "-1024414.5,84.1,-1017329.5"
            - name: "Lily and Bunny's Place (eightworld)"
              item: "prismarine"
              pos: "-1023961.2,83.1,-1017542.5"
            - name: "Harry Dom (eightworld)"
              lore: ["You know anything about this Idicam?"]
              item: "prismarine"
              pos: "-1023198.2,90.1,-1016255.4"
            - name: "EShaunTerror (eightworld)"
              lore: ["It was a nice wooden base before the terror"]
              item: "prismarine"
              pos: "-1025562.7,124,-1017778.5"
            - name: "Civilization (eightworld)"
              lore: []
              item: "prismarine"
              pos: "-1039296.2,86,-1021673.5"
            - name: "Crafting Dragon (eightworld)"
              item: "prismarine"
              pos: "-1026728.8,82,-1015043.3,27.5,-3.5"
            - name: "Creative Spawn"
              lore: ["Follow the path up the trees for a surprise :)"]
              item: "sponge"
              pos: "-2560008.5,80,-1024029.5"
            - name: "DJ S3rl (creative)"
              item: "sponge"
              pos: "-2559967.5,65,-1019418.5"
            - name: "Nether Road (creative)"
              lore: ["Built by The_Ramen_God"]
              item: "sponge"
              pos: "-2556020.5,65,-1035307.5"
            - name: "Peasent Village (creative)"
              lore: ["shoo shoo"]
              item: "sponge"
              pos: "-2557114.5,65,-1038388.5"
            - name: "CheesePuff422's House"
              item: "sponge"
              pos: "-6038324.5,65,-1509911.0"