description: "The museum world!"



worlds:
  map:
    folder: "museum"
    environment: "normal"
    type: "saved"
    spawn:
      x: -199950.5
      y: 124.1
      z: -299979.5
    game_rules: &game_rules
      doMobLoot: false
      mobGriefing: false
  map_nether:
    folder: "museum_nether"
    environment: "nether"
    type: "saved"
    game_rules: *game_rules
  map_the_end:
    folder: "museum_the_end"
    environment: "the_end"
    type: "saved"
    game_rules: *game_rules

custom_items:
  warp_chooser:
    display_name_locale: "museum_teleporter.name"
    material: "COMPASS"
    listeners:
      warp:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.util.item.WarpChooser"
        config:
          title_locale: "museum_teleporter.title"
          warps:
            - name: "&cOriginal Hut"
              item: "wool,1,14"
              lore: ["Where it all started..."]
              pos: "-180,75,998422"
            - name: "&cOriginal Flair"
              item: "wool,1,14"
              lore: ["Flair is created!"]
              pos: "-216,65,998116"
            - name: "&cFort Fiare"
              item: "wool,1,14"
              lore: ["We gonna burn."]
              pos: "5262,72,998469"
            - name: "&eGigaCavern"
              item: "wool,1,4"
              lore: ["My first proper survival world"]
              pos: "251051,68,-1049598"
            - name: "&eThe Base Between"
              item: "wool,1,4"
              lore: ["To link up GigaCavern and the rest of the Random Seed bases"]
              pos: "251387,70,-1049848"
            - name: "&eFort Factory Mob"
              item: "wool,1,4"
              lore: ["Do you know how to make a mob farm?"]
              pos: "251443,64,-1049008"
            - name: "&eSandy Mines"
              item: "wool,1,4"
              lore: ["Literally the only mine with a (once) working cart system"]
              pos: "251760,30,-1049703"
            - name: "&eThe Vault"
              item: "wool,1,4"
              lore: ["Where better to store your nice diamonds?"]
              pos: "251842,64,-1051083"
            - name: "&aThe Hut (OG1)"
              item: "wool,1,13"
              lore: ["Hooray for the first server!"]
              pos: "199557,68,-1049584"
            - name: "&aCacti and Reeds (OG1)"
              item: "wool,1,13"
              lore: ["The cacti quest has begun. Not that we went far"]
              pos: "199538,64,-1049121"
            - name: "Eightworld Spawn"
              item: "prismarine"
              lore: ["The second world on Ithinkrok's Factions"]
              pos: "-1025925.5,89.5,-1021670.5"
            - name: "Griefed Faction Base (eightworld)"
              item: "prismarine"
              lore: ["bosscamcam123 is the Manager / Boss"]
              pos: "-1025380.5,92,-1021470.5"
            - name: "xxsniper7xx's Base (eightworld)"
              lore: ["Look inside :)"]
              item: "prismarine"
              pos: "-1024292.5,91.5,-1023633.5"
            - name: "Samuel's Drug Pub (eightworld)"
              lore: ["It's a bit of a mess, I know :P"]
              item: "prismarine"
              pos: "-1026355.15,71.03,-1025038.06"
            - name: "Jofly's Home (eightworld)"
              lore: ["People to Spare: bosscamcam123"]
              item: "prismarine"
              pos: "-1024059.5,87.1,-1017374.5"
            - name: "Jofly's Trading Post (eightworld)"
              lore: ["NO REFUNDS"]
              item: "prismarine"
              pos: "-1024414.5,84.1,-1017329.5"
            - name: "Lily and Bunny's Place (eightworld)"
              item: "prismarine"
              pos: "-1023961.2,83.1,-1017542.5"
            - name: "Harry Dom (eightworld)"
              lore: ["You know anything about this Idicam?"]
              item: "prismarine"
              pos: "-1023198.2,90.1,-1016255.4"